### ISSUE TITLE
linux build of NetExample fails due to linking

### ISSUE THREAD

**Issue by luckyhacky** [rosc77/CoreSDK#2]
Linking on linux fails for NetExample, because "-L" is missing in generated link.txt
`/home/<user>/projects/CoreSDK/lib/libCoreSDK.a: error adding symbols: bad value`

adding -L resolves the issue: `~/projects/CoreSDK/examples/build/net/CMakeFiles/NetExample.dir/link.txt `

`usr/bin/c++  -fPIC  -std=c++11 -ldl -fPIC -std=c++11 -ldl -fPIC -g  -shared -Wl,-soname,libNetExample.so -o ../../net/bin/libNetExample.so CMakeFiles/NetExample.dir/src/main.cpp.o -L /home/<user>/projects/CoreSDK/lib/libCoreSDK.a -ldl -lpthread`

Globally adding -L to CMakeBase.txt will break hello example, which has no "-shared" in it but "-rdynamic"
`target_link_libraries (${PROJECT_NAME} LINK_PUBLIC -L ${CMAKE_DL_LIBS})`

**Comment by rosc77** [comment]
Not reproducable on

- Ubuntu 16.10 x64
- Ubuntu 16.10 x86
- RaspberryPi / Raspbian GNU/Linux 8.0 (jessie)
- (of course) Windows 10 x64

**Comment by luckyhacky** [comment]
used a97b41d - seem to be broken.
current head is working.

**Comment by luckyhacky** [comment]
confirmed on Ubuntu 16.04 x64
